language: objective-c
osx_image: xcode8
xcode_project: EZAnimation.xcodeproj
xcode_scheme: EZAnimation

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version

script:
- set -o pipefail
- xcodebuild -project EZAnimation.xcodeproj -target EZAnimation -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

